commit to branch supraja
PLaxmiPrasanna/OnlineMovieTicketSystem pull request #2
Opened 2020-10-06 10:49 UTC by vempalisupraja

Testing pull request. Added some abstract methods to IAdminDAO.

2020-10-07 18:36 UTC, PLaxmiPrasanna commented on src/com/cap/omts/dao/AdminDAOImpl.java
> -		int insertedRows;
please rename the variable appropriately. Here I suggest you to rename it as isInserted and initialize it to zero.

2020-10-07 18:37 UTC, PLaxmiPrasanna commented on src/com/cap/omts/dao/AdminDAOImpl.java
>  				}
close the database connection

2020-10-07 18:57 UTC, PLaxmiPrasanna reviewed
please do the changes as commented on each part.

2020-10-07 18:57 UTC, PLaxmiPrasanna commented on src/com/cap/omts/dao/AdminDAOImpl.java
please change the insertedRows variable to an appropriate name. I suggest you to name it as isInserted and initialise it.

2020-10-07 18:57 UTC, PLaxmiPrasanna commented on src/com/cap/omts/dao/AdminDAOImpl.java
> +
Please remove this comment

2020-10-07 18:57 UTC, PLaxmiPrasanna commented on src/com/cap/omts/dao/AdminDAOImpl.java
> +				System.out.println(resultSet.getInt(1)+"  "+resultSet.getString(2)+"  "+resultSet.getString(3)+" "+resultSet.getString(4)+" "+resultSet.getString(5));
please remove this syso statement

2020-10-07 18:57 UTC, PLaxmiPrasanna commented on src/com/cap/omts/dao/AdminDAOImpl.java
> +	 */
please remove comments

2020-10-07 19:03 UTC, PLaxmiPrasanna requested changes
please do the mentioned changes

2020-10-08 02:41 UTC, vempalisupraja commented
The changes requested are reflected.

2020-10-08 02:41 UTC, closed without merging